// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvsnsjsvswmtgqqzryms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2c25zanN2c3dtdGdxcXpyeW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTU2NTksImV4cCI6MjA3MTM5MTY1OX0.wnrYjfcx2m7EZE0SbfR2N5YxiBWpJseb7vOpE5iYr7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});